baseURL = "https://carlosadean.eti.br/"
languageCode = "en-us"
title = "Carlos Adean"
theme = "anatole"
paginate = "10"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

#[markup]
#    [markup.goldmark]
#        [markup.goldmark.renderer]
#        unsafe=true

#[taxonomies]
#    category = "categories"
#    series = "series"
#    tag = "tags"

#[related]
#  includeNewer = true
#  threshold = 80
#  toLower = true

#[[related.indices]]
#  name = 'keywords'
#  weight = 100

#[[related.indices]]
#  name = 'tags'
#  weight = 80

[params]
title = "Carlos Adean"
author = "Carlos Adean"
description = "Dicas práticas do meu dia a dia como sysadmin e anotações diversas."
profilePicture = "images/carlosadean.jpg"
copyright = "2020-{{ YEAR }}"
displayMode = "dark"
hidesidebar = false
mainSections = ["posts"]

# date format
#singleDateFormat = "Mon, Jan 2, 2006"
#indexDateFormat = "Mon, Jan 2, 2006"
#listDateFormat = "Jan 2"
singleDateFormat = "02/01/2006"
indexDateFormat = "02/01/2006"
listDateFormat = "02/01/2006"

contentratio = 0.7
readMore = true
postSectionName = "blog"
contactFormAction = "https://formspree.io/f/mwkgryal"
reversepagetitle = true
disableTitleCapitalization = true

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/carlosadean"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/carlosadean"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:carlosadean@gmail.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"